INSERT INTO Pupper VALUES ('John Smith', 'Fido', test.jpg, 'Small', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('Jane Smith', 'Max', test.jpg, 'Small', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('Jane Doe', 'Ace', test.jpg, 'Small', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('Roger Darling', 'Rolly', test.jpg, 'Small', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('Kevin DiCicco', 'Air Buddy', test.jpg, 'Medium', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('John Doe', 'Lucky', test.jpg, 'Medium', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('Darling', 'Lady', test.jpg, 'Medium', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('Jim Dear', 'Tramp', test.jpg, 'Medium', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('George Newton', 'Beethoven', test.jpg, 'Large', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('Matt Turner', 'Lassie', test.jpg, 'Large', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes' );
INSERT INTO Pupper VALUES ('Tom Hanks', 'Hooch', test.jpg, 'Large', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes' );